### ISSUE TITLE
Adapt SAREF4CITY to SAREF 3.0

### ISSUE THREAD

**Issue by mariapoveda** [mariapoveda/saref-ext#50]
It is planned that SAREF 3.0 models FeatureOfInterest and related properties therefore the elements declared in SAREF4CITY namespace should be replaced by SAREF new ones.

**Comment by jonimoreira** [comment]
Hi @mariapoveda , I'm interested on that and I wonder if there is a roadmap/plan for SAREF 3.0. 

From my previous work, I would recommend to move some conceptualizations to the SAREF core:

1- Frequency predicates from SAREF4envi => btw, we used the examples in an experiment w.r.t JSON-LD as payload for data exchange:
Paper: https://onlinelibrary.wiley.com/doi/abs/10.1002/9781119564034.ch20
GitHub: https://github.com/jonimoreira/JSON-LD

2- Time series predicates => work done within the context of "SAREF4health" extension:
Paper: http://www.ebooks.iospress.com/volumearticle/50262
GitHub: https://github.com/jonimoreira/INTER-IoT-EWS/tree/master/WP1-Ontology%20translations%20and%20rules/src/Ontologies/SAREF

Let me know if I can help on that. Cheers!

**Comment by mariapoveda** [comment]
Thanks, I'll pass the message to the SAREF internal discussions.
