### ISSUE TITLE
Reuse SSN for platform, system and deployment

### ISSUE THREAD

**Issue by mariapoveda** [mariapoveda/saref-ext#52]
As the current proposal for modelling of SAREF4AGRI for platform, system and deployment has been taken from SSN and no changes has been proposed, it would be better to directly reuse SSN URIs.

**Comment by jonimoreira** [comment]
I think reusing SSN predicates is a good choice. 
I know that INTER-IoT project used and I think it worth looking into the lessons learned. In particular, look into the core ontology produced (Generic Ontology of IoT Platforms), which reuse these terms:
https://docs.inter-iot.eu/ontology/
